### PR TITLE
Updated TimeSync configuration script

### PR DESCRIPTION
**Pull request by ilenghel**
Updated time sync configuration script to address issue #764

### CODE REVIEW

**Comment by chvalean** [comment]
@lixuemin2016 can you please also verify these changes and let us know if you have any feedback.
Thank you!

**Comment by lixuemin2016** [comment]
@chvalean @ilenghel  we are checking these changes, will update the feedback in recent two days. Thank you so much.

**Comment by ilenghel** [comment]
Thank you for the feedback. Regarding "return $ptp", it shall be removed. LinuxPTP provides ptp4l and that is why we need to install it. About moving some of the lines to separate functions, because we have to handle different distributions, some of the lines will still repeat. Thank you.

**Comment by lixuemin2016** [comment]
Thank you, base on comment from developer,  he suggests that we no need to cover linuxptp/ptp4l here -  "these are for 'real' PTP devices and their configuration and we're just piggy-backing on PTP protocol." Could you please set the install linuxptp/ptp4l as optional, or not add this part to RHEL case? Thank you so much.

**Comment by chvalean** [comment]
Hi Li,
The ptp4l appeared in the initial commit with the chronny off new tests.
If we don't rely on linuxptp/ptp4l, then we need to remove all the installation and configuration for that.

**Comment by lixuemin2016** [comment]
@chvalean, agree to remove all the installation and configuration for ptp4l based on developer Vitaly's comment.
Thank you so much.

**Pull request merged**
