### PR TITLE
kdump_nfs: check modules for kdump.img before execute kdump

### PR DESCRIPTION
**Pull request by HuijingHei**

### CODE REVIEW

**Comment by HuijingHei** [comment]
Add hyperv_fb module because of bug https://bugzilla.redhat.com/show_bug.cgi?id=1603017

**Comment by chvalean** [comment]
Hi @HuijingHei .
I'm curious in which distros/kernels is the initramfs-`uname -r`kdump.img used.

**Comment by HuijingHei** [comment]
> Hi @HuijingHei .
> I'm curious in which distros/kernels is the initramfs-`uname -r`kdump.img used.

Hi Chris, thanks for you review. 

My understanding is you want to ask which initramfs-`uname -r`kdump.img includes hyperv_fb module?
Actually the modules whether included in kdump.img depends on kexec-tools-2.0.15-20.el7.x86_64. 

The latest rhel7.6/kernel-3.10.0-957.el7 with kexec-tools-2.0.15-20.el7 includes the hyperv_fb module, the older versions does not include hyper_fb. If needed I will add condition for modules check for new kernel version, and skip for older version.

Best Regards
Huijing Hei

**Comment by HuijingHei** [comment]
Close this request and open a new request https://github.com/LIS/lis-test/pull/1142

**Pull request closed without merging**
